package designloginandregister;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omar
 */
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import designloginandregister.LoginForm;
import javax.swing.JFrame;

public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public String username;
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldusername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonRegister = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordcon = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 197, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 57));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, -1, 38));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 432, 90));

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jTextFieldusername.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldusername.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(jTextFieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 188, -1));

        jPassword.setBackground(new java.awt.Color(108, 122, 137));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 188, -1));

        jButtonRegister.setBackground(new java.awt.Color(255, 197, 0));
        jButtonRegister.setFont(new java.awt.Font("Gill Sans", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 91, 38));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Gill Sans", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(48, 48, 48));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 91, 38));

        jLabel6.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 92, -1));

        jTextFieldname.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldname.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(jTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 188, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("ComfirePassword:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jPasswordcon.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordcon.setForeground(new java.awt.Color(228, 241, 254));
        jPasswordcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordconActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 188, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 432, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = jTextFieldname.getText();
        username = jTextFieldusername.getText().toString();
        String password = String.valueOf(jPasswordcon.getPassword());
        String conpassword = String.valueOf(jPasswordcon.getPassword());
        if (verifyFields()) {
            if (!checkUsername(username)) {
                PreparedStatement ps;
                ResultSet rs;
                String query = "INSERT INTO `users`(`username`, `password`, `Firstname-Lastname`) VALUES (?,?,?)";
                
                try {
                    My_CNK con = new My_CNK();
                    ps = con.ConnectDataBase().prepareStatement(query);
                    ps.setString(1, username);
                    ps.setString(2, password);
                    ps.setString(3, name);
                    if (ps.executeUpdate() >= 0) {
                        JOptionPane.showMessageDialog(null, "New User Add");
                    }
                    
                    
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jPasswordconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordconActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordcon;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables

    private boolean verifyFields() {
        this.username = jTextFieldusername.getText();
           String password = String.valueOf(jPasswordcon.getPassword());
           String conpassword = String.valueOf(jPasswordcon.getPassword());
    
           if (username.trim().equals("") || password.trim().equals("") || conpassword.trim().equals("") ) {
               JOptionPane.showMessageDialog(null, "โปรดใส่ข้อมูลให้ครบด้วยนะ", "มีข้อมูลที่ไม่ได้กรอก", 2);
               return false;
           }
           // check if the two password 
           else if(!password.equals(conpassword)){
               JOptionPane.showMessageDialog(null, "กรุณาใส่ Password ให้ถูกต้อง", "ยืนยัน Password", 2);
               return false;
           }
           
       
       // if everything is collect
           else{
               return true;
           }
    }

    private boolean checkUsername(String username) {
                   PreparedStatement st;
           ResultSet rs;
           boolean username_exist = false;
           
           String query = "SELECT * FROM `users` WHERE `username` = ?";
           
        try {
            My_CNK con = new My_CNK();
            st = con.ConnectDataBase().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if (rs.next()) {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "ชื่อผู้ใช้นี้มีคนใช้เเล้ว", "Username Failed", 2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           return username_exist;
    }
}
